# Generated by Django 6.0.3 on 2026-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviacategory',
            name='sport',
            field=models.CharField(choices=[('mlb', 'MLB'), ('nfl', 'NFL')], default='mlb', max_length=20),
        ),
    ]
