# Generated by Django 6.0.3 on 2026-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_triviacategory_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviacategory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
