# Generated by Django 6.0.3 on 2026-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_triviacategory_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviacategory',
            name='recommended_pinpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triviacategory',
            name='total_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
