# Generated by Django 6.0.3 on 2026-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_triviacategory_recommended_pinpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.CharField(choices=[('mlb', 'MLB'), ('nfl', 'NFL')], default='mlb', max_length=20),
        ),
        migrations.AddField(
            model_name='triviacategory',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='trivia_categories', to='myapp.player'),
        ),
    ]
